[package]
name = "advent-of-code"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "trebuchet"
path = "src/trebuchet/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
